import { fallbackDocuments } from "@/features/documents";
import type {
  AdminDocument,
  EvaluationDataset,
  EvaluationRunSummary,
  FeedbackItem,
  IngestionJob,
  RetrievalPlaygroundResult,
} from "./types";

const sampleDate = "2026-07-15T08:30:00Z";

export const fallbackAdminDocuments: AdminDocument[] = [
  {
    ...fallbackDocuments[1],
    issuer: "Pemerintah Republik Indonesia",
    verification_status: "verified",
    source_verification_status: "verified",
    legal_review_status: "verified",
    ingestion_status: "completed",
    chunk_count: 186,
    publication_status: "published",
    version: 3,
    updated_at: sampleDate,
    updated_by: "Admin",
    last_error: null,
    relationships: [
      {
        from_document_id: "PP-35-2021",
        to_document_id: "UU-6-2023",
        relationship_type: "amended_by",
        confidence: "high",
        notes: "Perubahan ketentuan Cipta Kerja.",
      },
    ],
    versions: [
      { version: 3, status: "published", created_at: sampleDate, created_by: "Admin" },
      { version: 2, status: "published", created_at: "2026-07-10T10:00:00Z", created_by: "Admin" },
      { version: 1, status: "draft", created_at: "2026-07-01T09:00:00Z", created_by: "System" },
    ],
  },
  {
    ...fallbackDocuments[0],
    issuer: "Pemerintah Republik Indonesia",
    verification_status: "pending_detail_url",
    source_verification_status: "pending",
    legal_review_status: "pending",
    ingestion_status: "needs_review",
    chunk_count: 112,
    publication_status: "draft",
    version: 2,
    updated_at: "2026-07-14T07:20:00Z",
    updated_by: "Admin",
    last_error: "Dua heading tidak terdeteksi sebagai struktur pasal.",
    relationships: [],
    versions: [
      { version: 2, status: "draft", created_at: sampleDate, created_by: "Admin" },
      { version: 1, status: "draft", created_at: "2026-07-01T09:00:00Z", created_by: "System" },
    ],
  },
  {
    document_id: "PP-36-2021",
    title: "Peraturan Pemerintah Nomor 36 Tahun 2021 tentang Pengupahan",
    short_title: "PP 36/2021",
    regulation_type: "PP",
    number: 36,
    year: 2021,
    legal_status: "needs_verification",
    topics: ["pengupahan", "upah_minimum"],
    source_url: "https://peraturan.bpk.go.id/",
    pdf_url: "/documents/PP-36-2021/pdf",
    issuer: "Pemerintah Republik Indonesia",
    verification_status: "pending_detail_url",
    source_verification_status: "pending",
    legal_review_status: "pending",
    ingestion_status: "failed",
    chunk_count: 0,
    publication_status: "draft",
    version: 1,
    updated_at: "2026-07-13T05:15:00Z",
    updated_by: "System",
    last_error: "Ekstraksi PDF gagal pada halaman 44.",
    relationships: [],
    versions: [{ version: 1, status: "draft", created_at: sampleDate, created_by: "System" }],
  },
];

export const fallbackIngestionJobs: IngestionJob[] = [
  {
    job_id: "ing_001",
    document_id: "PP-35-2021",
    status: "completed",
    created_at: sampleDate,
    updated_at: sampleDate,
    result: { chunk_count: 186, warnings: [] },
  },
  {
    job_id: "ing_002",
    document_id: "UU-13-2003",
    status: "needs_review",
    created_at: "2026-07-14T07:00:00Z",
    updated_at: "2026-07-14T07:20:00Z",
    error: "Dua heading tidak terdeteksi sebagai struktur pasal.",
  },
  {
    job_id: "ing_003",
    document_id: "PP-36-2021",
    status: "failed",
    created_at: "2026-07-13T05:00:00Z",
    updated_at: "2026-07-13T05:15:00Z",
    error: "Ekstraksi PDF gagal pada halaman 44.",
  },
];

export const fallbackFeedback: FeedbackItem[] = [
  {
    feedback_id: "fb_001",
    user_id: "user@example.com",
    question: "Apakah pekerja PKWT mendapat kompensasi?",
    rating: "helpful",
    comment: "Kutipan pasalnya jelas.",
    created_at: sampleDate,
  },
  {
    feedback_id: "fb_002",
    user_id: "anonymous",
    question: "Bagaimana hitungan pesangon karena efisiensi?",
    rating: "not_helpful",
    issue_category: "citation_incorrect",
    comment: "Sumber yang tampil belum membahas kondisi perusahaan saya.",
    created_at: "2026-07-14T06:10:00Z",
  },
];

export const fallbackRetrievalResults: RetrievalPlaygroundResult[] = [
  {
    chunk_id: "pp35-2021-p15-c1",
    document_id: "PP-35-2021",
    short_title: "PP 35/2021",
    article: "Pasal 15",
    page_start: 13,
    page_end: 13,
    quote:
      "Pengusaha wajib memberikan uang kompensasi kepada pekerja/buruh yang hubungan kerjanya berdasarkan PKWT.",
    lexical_score: 0.61,
    semantic_score: 0.88,
    rerank_score: 0.92,
    final_score: 0.92,
    match_reasons: ["topic:pkwt", "article_match"],
  },
  {
    chunk_id: "pp35-2021-p16-c1",
    document_id: "PP-35-2021",
    short_title: "PP 35/2021",
    article: "Pasal 16",
    page_start: 14,
    page_end: 14,
    quote: "Besaran uang kompensasi diberikan sesuai masa kerja pekerja/buruh.",
    lexical_score: 0.54,
    semantic_score: 0.82,
    rerank_score: 0.87,
    final_score: 0.87,
    match_reasons: ["context_expansion"],
  },
];

export const fallbackEvaluationDataset: EvaluationDataset = {
  dataset_id: "evalset_golden_v1",
  name: "KerjaPedia Golden Questions v1",
  created_at: "2026-07-20T10:00:00Z",
  questions: [
    {
      question_id: "q_upah_minimum_001",
      category: "pengupahan",
      question: "Siapa yang menetapkan upah minimum provinsi?",
      expected_answer: "Gubernur menetapkan upah minimum provinsi.",
      expected_document_ids: ["PP-36-2021"],
      expected_articles: ["Pasal 24"],
      expected_topics: ["upah_minimum"],
      should_refuse: false,
      hard_negative: false,
      status: "verified",
    },
    {
      question_id: "q_pkwt_kompensasi_002",
      category: "pkwt",
      question: "Apakah pekerja PKWT berhak atas uang kompensasi?",
      expected_answer: "Ya, pekerja PKWT berhak atas uang kompensasi.",
      expected_document_ids: ["PP-35-2021"],
      expected_articles: ["Pasal 15"],
      expected_topics: ["pkwt"],
      should_refuse: false,
      hard_negative: true,
      status: "verified",
    },
    {
      question_id: "q_phk_severance_003",
      category: "phk",
      question: "Berapa besaran uang pesangon untuk masa kerja 8 tahun?",
      expected_answer: "Uang pesangon 9 kali upah untuk masa kerja 8 tahun.",
      expected_document_ids: ["UU-13-2003"],
      expected_articles: ["Pasal 156"],
      expected_topics: ["phk"],
      should_refuse: false,
      hard_negative: false,
      status: "needs_human_review",
    },
  ],
};

export const fallbackEvaluationRuns: EvaluationRunSummary[] = [
  {
    run_id: "evalrun_sample_001",
    dataset_id: "evalset_golden_v1",
    created_at: "2026-07-29T09:00:00Z",
    metrics: {
      hybrid: {
        question_count: 3,
        answerable_count: 3,
        refusal_count: 0,
        recall_at_5: 1.0,
        mean_reciprocal_rank: 0.8889,
        citation_correctness: 0.8333,
        faithfulness: 0.9,
        refusal_accuracy: 1.0,
        hard_negative_recall_at_5: 1.0,
      },
      rerank: {
        question_count: 3,
        answerable_count: 3,
        refusal_count: 0,
        recall_at_5: 1.0,
        mean_reciprocal_rank: 0.9444,
        citation_correctness: 0.8333,
        faithfulness: 0.9333,
        refusal_accuracy: 1.0,
        hard_negative_recall_at_5: 1.0,
      },
      baseline: {
        question_count: 3,
        answerable_count: 2,
        refusal_count: 1,
        recall_at_5: 0.6667,
        mean_reciprocal_rank: 0.5,
        citation_correctness: 0.5,
        faithfulness: 0.7,
        refusal_accuracy: 0.6667,
        hard_negative_recall_at_5: 0.5,
      },
    },
  },
  {
    run_id: "evalrun_sample_002",
    dataset_id: "evalset_golden_v1",
    created_at: "2026-07-22T14:30:00Z",
    metrics: {
      hybrid: {
        question_count: 3,
        answerable_count: 3,
        refusal_count: 0,
        recall_at_5: 0.8333,
        mean_reciprocal_rank: 0.7222,
        citation_correctness: 0.6667,
        faithfulness: 0.8,
        refusal_accuracy: 1.0,
        hard_negative_recall_at_5: 0.6667,
      },
      rerank: {
        question_count: 3,
        answerable_count: 3,
        refusal_count: 0,
        recall_at_5: 0.8333,
        mean_reciprocal_rank: 0.7778,
        citation_correctness: 0.6667,
        faithfulness: 0.8333,
        refusal_accuracy: 1.0,
        hard_negative_recall_at_5: 0.6667,
      },
    },
  },
];
